### PR TITLE
Create FOSSassets Too Big

### PR DESCRIPTION
**Pull request by crhy**
We are replacing all the original Civ2 Multiplayer Gold assets with AI generated upscaled artwork.  For the eventual release of a completely free and Open Source version of Civ 2, hopefully portable to Android.

### CODE REVIEW

**Comment by crhy** [comment]
So far all the images are uploaded here: https://github.com/axx0/Civ2-clone/tree/master/RaylibUI/FOSS%20art

**Comment by crhy** [comment]
cold-war-submarine-breached-from-above-zoom-out-930421331
world-war-2-aircraft-carrier-in-the-open-ocean-from-above-930421331 (1)
world-war-2-aircraft-carrier-in-the-open-ocean-from-above-930421331
two-napolean-era-dragoons-in-battle-887176028
two-men-in-blue-uniforms-firing-rifles-in-the-1800s-235577188
two-men-in-blue-uniforms-kneeling-and-firing-rifles-in-the-1800s-339333675
paratrooper-actively-parachuting-274011233
two-angry-medeival-men-in-iron-helmets-holding-pikes-502227578
two-angry-partisans-holding-rifles-over-their-heads-wearing-black-uniforms-862951040
a-ww2-german-submarine-on-the-open-ocean-from-above-36663140
two-war-elephants-on-attack-40613638
two-battle-weary-marines-holding-their-weapons-from-above-168226193
a-humvee-with-machine-gun-mounted-on-top-from-above-999311884
a-humvee-with-machine-gun-mounted-from-above-25065260
a-1600s-galleon-from-above-with-sails-deployed-on-the-open-ocean-843972639
a-1600s-galleon-from-above-with-sails-deployed-402904649
a-1700s-frigate-from-above-with-sails-deployed-979574648
a-frigate-from-above-335073257
two-men-on-horses-carrying-spears-780223548
apache-helicopter-271976486
two-angry-men-in-crimson-robes-holding-torches
two-angry-men-in-crimson-robes-holding-torches-460223480
two-men-of-different-ethnicity-in-loincloths-with-ancient-shovels-658531085
two-standing-mountain-men-in-coon-skin-caps-842153717
uss-troop-transport-world-war-2-683373936
uss-cruiser-308610912
uss-destroyer-579889387
bismark-battleship-468442743
uss-lexington-with-spitfire-flying-above-in-the-open-ocean-479989699
civil-war-era-ironclad-606863511
ancient-single-square-sail-trireme-520218352
trireme-sailing-523684153
two-barbarians-673963326
barbarians-436644603
a--wooden-roman-trebuchet-868855323
two-roman-phalanx-soldiers-526099904
american-cavalry-in-blue-uniforms-without-flags-426516538
cavalry-632868070
two-modern-howitzers-one-firing-699579477
two-world-war-2-cannons-one-firing-722742014
two-panzers-one-firing
two-panzers-one-firing-872530603
two-alpine-troops-in-snow-camoflauge-carrying-ak-47s-standing-on-a-rocky-mountain-peak-472956926
two-riflemen-wearing-blue-uniforms-in-the-late-1800s-one-firing-his-rifle-623389968
a-diplomat-with-a-top-hat-from-the-1800s-521461941
a-sexy-female-spy-wearing-all-black-with-sunglasses-45855650
two-mounted-dragoons-one-firing-a-musket-367586089
two-napolean-era-cannons-one-firing-8397214
two-b-17-bombers-flying-in-formation-from-above-368759508
two-p-71-black-widows-flying-in-formation-from-above-646645186
two-stealth-fighters-flying-in-formation-from-above-819390806
two-stealth-bombers-flying-in-formation-from-above-103805642
two-neanderthals-thrusting-spears-in-unison-towards-towards-the-camera-256148996 (1)
two-musketeers-both-facing-the-camera-one-standing-and-firing-one-taking-a-knee-and-loading-their--256148996
two-world-one-era-machine-gunners-facing-the-camera-on-a-solid-green-background-256148996
two-musketeers-both-facing-the-camera-one-standing-and-firing-one-taking-a-knee-and-loading-their-
two-neanderthals-thrusting-spears-in-unison-towards-towards-the-camera
two-neanderthals-thrusting-spears-in-unison-towards-towards-the-camera-256148996

**Comment by crhy** [comment]
Terrain/Resources

a-clump-of-maple-trees-on-a-hill-in-the-summer-930421331
looking-down-on-a-densely-packed-clump-of-trees-on-a-solitary-grassy-hill-843333125
looking-down-on-a-brightly-colored-spice-plant-63031445
looking-down-on-a-swamp-669739572
looking-down-on-a-desolate-empty-tundra-943203929
looking-down-on-a-wine-bottle-in-the-grass-582060237
looking-down-on-a-silk-worm-farm-380196274
looking-down-on-a-yellow-grassy-plain-199602640
looking-down-on-a-wheat-field-from-high-above-544314316
looking-down-at-a-giant-pheasant-superimposed-over-a-small-clump-of-trees-752312133
looking-down-at-a-peat-bog-613337741
looking-down-at-the-open-ocean-from-5000-feet-in-the-air-117554509
looking-down-on-a-small-circular-desert-oasis-in-the-sand-at-noon-704194953
looking-down-on-dense-jungle-715505979
looking-down-on-a-single-walrus-with-tusks-on-ice-997680996
arial-view-solitary-snowy-mountain-peak-315637002
looking-down-on-an-iron-mine-in-the-side-of-a-snowy-mountain-peak-766986932
looking-down-on-isolated-grassy-hills-protruding-from-a-flat-plane-396202325
looking-down-on-a-viking-shield-laying-in-the-grass-404120637
looking-down-on-a-grassy-field-349297810
looking-down-on-a-gold-nugget-on-a-mountain-769938721
looking-down-on-an-oilwell-on-a-snowy-blue-antarctic-glacier-825736335
looking-down-on-a-snowy-blue-antarctic-glacier-788396010
looking-down-on-unpolished-gemstones-protruding-from-a-rock-face-325480085
looking-down-on-two-sheep-in-a-snowy-field-756065031
looking-down-on-two-beavers-frolicking-in-the-snow-388236889
looking-down-on-bananas-in-some-ferns-663947019
looking-down-on-a-whale-starting-to-breach-in-the-open-ocean
looking-down-on-a-salmon-jumping-out-of-the-water-in-the-open-ocean
desert-from-above-mid-day-with-oil-well
desert-from-above-mid-day
a-coal-mine-from-above
two-buffalo-facing-to-the-right-on-golden-grass-from-above

**Comment by crhy** [comment]
Wonders

adam-smiths-trading-company-422052647

the-apollo-program-422052647

ancient-greek-collosus-statue-422052647

a-modern-observatory-422052647

medical-symbol-overlayed-dna-helix-422052647

primate-family-tree-with-examples-422052647

the-eiffel-tower-over-a-sunset-in-the-colors-of-the-french-flag-422052647

the-great-library-of-alexandria-422052647

great-wall-of-china-under-siege-422052647

hanging-gardens-of-babylon-422052647

the-hoover-dam-at-sunset-422052647

sir-isaac-newton-holding-an-apple-422052647

johan-bach-playing-pipe-organ-422052647

king-richard-and-his-crusaders-pillaging-422052647

einstein-overlayed-detailed-sketches-of-atomic-reactions-422052647
magellans-fleet-from-above-422052647
leonardo-da-vinci-overlayed-on-his-detaild-blueprints-422052647
the-great-lighthouse-422052647
angry-suffragette-shouting-422052647
3d-female-symbol-422052647
the-female-symbol-large-overlayed-an-angry-suffragette-shouting-422052647
a-row-of-flags-at-the-united-nations-422052647
chinese-dragon-art-422052647
the-statue-of-liberty-being-installed-by-a-french-work-crew-in-elizabethan-times-422052647 (1)
the-statue-of-liberty-close-up-in-front-of-the-sunset-422052647
the-statue-of-liberty-being-installed-by-a-french-work-crew-in-elizabethan-times-422052647
shakespeare-talking-to-an-attractive-actress-from-a-distance-on-a-stage-in-the-globe-theater-422052647
shakespeare-talking-to-an-attractive-actress-422052647
arecibo-crop-circle-response-422052647
all-three-great-pyramids-at-giza-422052647
the-oracle-at-delphi-422052647
sistine-chapel-gorgeous-artwork-422052647
marco-polo-caravan-camels-422052647

**Comment by crhy** [comment]
I also put City Improvements and Technology over here.  It's not letting me upload them here for some reason.  https://github.com/crhy/Civ2-clone/tree/master/Civ2Gold

**Comment by axx0** [comment]
> I also put City Improvements and Technology over here. It's not letting me upload them here for some reason. https://github.com/crhy/Civ2-clone/tree/master/Civ2Gold

You have it in your repo, but you need to commit those changes to this PR. You can't upload it to my repo directly.
Also a couple of things - for units etc. you need to make the diamond in the image, meaning you need to cut off the bottom left&right portions just like in the original game.
Also the images are too large, shrink them to a reasonable size so that they can be displayed on a grid.

**Pull request closed without merging**
